// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTagsToItem(arg1, arg2) {
  return window['go']['main']['App']['AddTagsToItem'](arg1, arg2);
}

export function AutoGenerateTags(arg1, arg2) {
  return window['go']['main']['App']['AutoGenerateTags'](arg1, arg2);
}

export function BatchPermanentDelete(arg1) {
  return window['go']['main']['App']['BatchPermanentDelete'](arg1);
}

export function CleanupUnusedTags() {
  return window['go']['main']['App']['CleanupUnusedTags']();
}

export function CreateChatSession(arg1) {
  return window['go']['main']['App']['CreateChatSession'](arg1);
}

export function CreateClipboardItem(arg1) {
  return window['go']['main']['App']['CreateClipboardItem'](arg1);
}

export function CreateTag(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2, arg3, arg4);
}

export function CreateTagGroup(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTagGroup'](arg1, arg2, arg3, arg4);
}

export function DeleteChatSession(arg1) {
  return window['go']['main']['App']['DeleteChatSession'](arg1);
}

export function DeleteClipboardItem(arg1) {
  return window['go']['main']['App']['DeleteClipboardItem'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DeleteTagGroup(arg1) {
  return window['go']['main']['App']['DeleteTagGroup'](arg1);
}

export function EmptyTrash() {
  return window['go']['main']['App']['EmptyTrash']();
}

export function GenerateChatTags(arg1) {
  return window['go']['main']['App']['GenerateChatTags'](arg1);
}

export function GenerateChatTitle(arg1) {
  return window['go']['main']['App']['GenerateChatTitle'](arg1);
}

export function GenerateTagsForClipboardItem(arg1) {
  return window['go']['main']['App']['GenerateTagsForClipboardItem'](arg1);
}

export function GetCategoriesAndTags() {
  return window['go']['main']['App']['GetCategoriesAndTags']();
}

export function GetChatMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetChatMessages'](arg1, arg2, arg3);
}

export function GetChatSession(arg1) {
  return window['go']['main']['App']['GetChatSession'](arg1);
}

export function GetChatSessions() {
  return window['go']['main']['App']['GetChatSessions']();
}

export function GetClipboardItems(arg1, arg2) {
  return window['go']['main']['App']['GetClipboardItems'](arg1, arg2);
}

export function GetMostUsedTags(arg1) {
  return window['go']['main']['App']['GetMostUsedTags'](arg1);
}

export function GetRecentTags(arg1) {
  return window['go']['main']['App']['GetRecentTags'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSimilarTags(arg1, arg2) {
  return window['go']['main']['App']['GetSimilarTags'](arg1, arg2);
}

export function GetStatistics() {
  return window['go']['main']['App']['GetStatistics']();
}

export function GetTagGroups() {
  return window['go']['main']['App']['GetTagGroups']();
}

export function GetTagStatistics() {
  return window['go']['main']['App']['GetTagStatistics']();
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function GetTagsByGroup(arg1) {
  return window['go']['main']['App']['GetTagsByGroup'](arg1);
}

export function GetTagsForItem(arg1) {
  return window['go']['main']['App']['GetTagsForItem'](arg1);
}

export function GetTrashItems(arg1, arg2) {
  return window['go']['main']['App']['GetTrashItems'](arg1, arg2);
}

export function GetWindowState() {
  return window['go']['main']['App']['GetWindowState']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function MergeTags(arg1, arg2) {
  return window['go']['main']['App']['MergeTags'](arg1, arg2);
}

export function PermanentDeleteClipboardItem(arg1) {
  return window['go']['main']['App']['PermanentDeleteClipboardItem'](arg1);
}

export function RemoveTagsFromItem(arg1, arg2) {
  return window['go']['main']['App']['RemoveTagsFromItem'](arg1, arg2);
}

export function RestoreClipboardItem(arg1) {
  return window['go']['main']['App']['RestoreClipboardItem'](arg1);
}

export function SearchClipboardItems(arg1) {
  return window['go']['main']['App']['SearchClipboardItems'](arg1);
}

export function SearchTags(arg1) {
  return window['go']['main']['App']['SearchTags'](arg1);
}

export function SendChatMessage(arg1, arg2) {
  return window['go']['main']['App']['SendChatMessage'](arg1, arg2);
}

export function SendChatMessageStream(arg1, arg2) {
  return window['go']['main']['App']['SendChatMessageStream'](arg1, arg2);
}

export function SetScreenSize(arg1, arg2) {
  return window['go']['main']['App']['SetScreenSize'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function SuggestTags(arg1, arg2) {
  return window['go']['main']['App']['SuggestTags'](arg1, arg2);
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}

export function UpdateChatSession(arg1, arg2) {
  return window['go']['main']['App']['UpdateChatSession'](arg1, arg2);
}

export function UpdateClipboardItem(arg1) {
  return window['go']['main']['App']['UpdateClipboardItem'](arg1);
}

export function UpdateItemTags(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateItemTags'](arg1, arg2, arg3);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateTag(arg1) {
  return window['go']['main']['App']['UpdateTag'](arg1);
}

export function UpdateTagGroup(arg1) {
  return window['go']['main']['App']['UpdateTagGroup'](arg1);
}

export function UseClipboardItem(arg1) {
  return window['go']['main']['App']['UseClipboardItem'](arg1);
}
