// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchPermanentDelete(arg1) {
  return window['go']['main']['App']['BatchPermanentDelete'](arg1);
}

export function DeleteClipboardItem(arg1) {
  return window['go']['main']['App']['DeleteClipboardItem'](arg1);
}

export function EmptyTrash() {
  return window['go']['main']['App']['EmptyTrash']();
}

export function GetClipboardItems(arg1, arg2) {
  return window['go']['main']['App']['GetClipboardItems'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatistics() {
  return window['go']['main']['App']['GetStatistics']();
}

export function GetTrashItems(arg1, arg2) {
  return window['go']['main']['App']['GetTrashItems'](arg1, arg2);
}

export function GetWindowState() {
  return window['go']['main']['App']['GetWindowState']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function PermanentDeleteClipboardItem(arg1) {
  return window['go']['main']['App']['PermanentDeleteClipboardItem'](arg1);
}

export function RestoreClipboardItem(arg1) {
  return window['go']['main']['App']['RestoreClipboardItem'](arg1);
}

export function SearchClipboardItems(arg1) {
  return window['go']['main']['App']['SearchClipboardItems'](arg1);
}

export function SetScreenSize(arg1, arg2) {
  return window['go']['main']['App']['SetScreenSize'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}

export function UpdateClipboardItem(arg1) {
  return window['go']['main']['App']['UpdateClipboardItem'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UseClipboardItem(arg1) {
  return window['go']['main']['App']['UseClipboardItem'](arg1);
}
