// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchPermanentDelete(arg1) {
  return window['go']['main']['App']['BatchPermanentDelete'](arg1);
}

export function CreateChatSession(arg1) {
  return window['go']['main']['App']['CreateChatSession'](arg1);
}

export function CreateClipboardItem(arg1) {
  return window['go']['main']['App']['CreateClipboardItem'](arg1);
}

export function DeleteChatSession(arg1) {
  return window['go']['main']['App']['DeleteChatSession'](arg1);
}

export function DeleteClipboardItem(arg1) {
  return window['go']['main']['App']['DeleteClipboardItem'](arg1);
}

export function EmptyTrash() {
  return window['go']['main']['App']['EmptyTrash']();
}

export function GenerateChatTags(arg1) {
  return window['go']['main']['App']['GenerateChatTags'](arg1);
}

export function GenerateChatTitle(arg1) {
  return window['go']['main']['App']['GenerateChatTitle'](arg1);
}

export function GetChatMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetChatMessages'](arg1, arg2, arg3);
}

export function GetChatSession(arg1) {
  return window['go']['main']['App']['GetChatSession'](arg1);
}

export function GetChatSessions() {
  return window['go']['main']['App']['GetChatSessions']();
}

export function GetClipboardItems(arg1, arg2) {
  return window['go']['main']['App']['GetClipboardItems'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatistics() {
  return window['go']['main']['App']['GetStatistics']();
}

export function GetTrashItems(arg1, arg2) {
  return window['go']['main']['App']['GetTrashItems'](arg1, arg2);
}

export function GetWindowState() {
  return window['go']['main']['App']['GetWindowState']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function PermanentDeleteClipboardItem(arg1) {
  return window['go']['main']['App']['PermanentDeleteClipboardItem'](arg1);
}

export function RestoreClipboardItem(arg1) {
  return window['go']['main']['App']['RestoreClipboardItem'](arg1);
}

export function SearchClipboardItems(arg1) {
  return window['go']['main']['App']['SearchClipboardItems'](arg1);
}

export function SendChatMessage(arg1, arg2) {
  return window['go']['main']['App']['SendChatMessage'](arg1, arg2);
}

export function SetScreenSize(arg1, arg2) {
  return window['go']['main']['App']['SetScreenSize'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}

export function UpdateChatSession(arg1, arg2) {
  return window['go']['main']['App']['UpdateChatSession'](arg1, arg2);
}

export function UpdateClipboardItem(arg1) {
  return window['go']['main']['App']['UpdateClipboardItem'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UseClipboardItem(arg1) {
  return window['go']['main']['App']['UseClipboardItem'](arg1);
}
