// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function BatchPermanentDelete(arg1:Array<string>):Promise<void>;

export function DeleteClipboardItem(arg1:string):Promise<void>;

export function EmptyTrash():Promise<void>;

export function GetClipboardItems(arg1:number,arg2:number):Promise<Array<models.ClipboardItem>>;

export function GetSettings():Promise<models.Settings>;

export function GetStatistics():Promise<models.Statistics>;

export function GetTrashItems(arg1:number,arg2:number):Promise<Array<models.ClipboardItem>>;

export function GetWindowState():Promise<models.WindowState>;

export function HideWindow():Promise<void>;

export function PermanentDeleteClipboardItem(arg1:string):Promise<void>;

export function RestoreClipboardItem(arg1:string):Promise<void>;

export function SearchClipboardItems(arg1:models.SearchQuery):Promise<models.SearchResult>;

export function SetScreenSize(arg1:number,arg2:number):Promise<void>;

export function ShowWindow():Promise<void>;

export function ToggleWindow():Promise<void>;

export function UpdateClipboardItem(arg1:models.ClipboardItem):Promise<void>;

export function UpdateSettings(arg1:models.Settings):Promise<void>;

export function UseClipboardItem(arg1:string):Promise<void>;
